export const SETTINGS_STORE = "opencode.settings"
export const DEFAULT_SERVER_URL_KEY = "defaultServerUrl"
export const WSL_SERVERS_KEY = "wslServers"
export const PINCH_ZOOM_ENABLED_KEY = "pinchZoomEnabled"
export const ENV_DOCTOR_STUDIO_PATH_KEY = "envDoctorStudioPath"
export const ENV_DOCTOR_INITIAL_SHOWN_KEY = "envDoctorInitialShown"
